/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminImpactRouteImport } from './routes/admin.impact'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpactRoute = AdminImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/work': typeof WorkRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/work': typeof WorkRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/work': typeof WorkRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/projects'
    | '/sitemap.xml'
    | '/volunteer'
    | '/work'
    | '/admin/blogs'
    | '/admin/contacts'
    | '/admin/donations'
    | '/admin/gallery'
    | '/admin/impact'
    | '/admin/newsletter'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/volunteers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/projects'
    | '/sitemap.xml'
    | '/volunteer'
    | '/work'
    | '/admin/blogs'
    | '/admin/contacts'
    | '/admin/donations'
    | '/admin/gallery'
    | '/admin/impact'
    | '/admin/newsletter'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/volunteers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/projects'
    | '/sitemap.xml'
    | '/volunteer'
    | '/work'
    | '/admin/blogs'
    | '/admin/contacts'
    | '/admin/donations'
    | '/admin/gallery'
    | '/admin/impact'
    | '/admin/newsletter'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/volunteers'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VolunteerRoute: typeof VolunteerRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impact': {
      id: '/admin/impact'
      path: '/impact'
      fullPath: '/admin/impact'
      preLoaderRoute: typeof AdminImpactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminImpactRoute: typeof AdminImpactRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogsRoute: AdminBlogsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminImpactRoute: AdminImpactRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VolunteerRoute: VolunteerRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
